In [2]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
import lxml.html as lh

In [3]:
url = "https://www.finder.com/global-netflix-library-totals"

In [4]:
#Create a handle, page, to handle the contents of the website
page = requests.get(url)
#Store the contents of the website under doc
doc = lh.fromstring(page.content)
#Parse data that are stored between <tr>..</tr> of HTML
tr_elements = doc.xpath('//tr')

In [5]:
tr_elements = doc.xpath('//tr')
#Create empty list
col=[]
i=0
#For each row, store each first element (header) and an empty list
for t in tr_elements[0]:
    i+=1
    name=t.text_content()
    print('%d:"%s"'%(i,name))
    col.append((name,[]))

1:"Country"
2:"# of TV Shows"
3:""
4:"# of Movies"
5:""

In [6]:
#Since out first row is the header, data is stored on the second row onwards
for j in range(1,len(tr_elements)):
    #T is our j'th row
    T=tr_elements[j]
    
    #If row is not of size 10, the //tr data is not from our table 
    if len(T)!=5:
        break
    
    #i is the index of our column
    i=0
    
    #Iterate through each element of the row
    for t in T.iterchildren():
        data=t.text_content() 
        #Check if row is empty
        if i>0:
        #Convert any numerical value to integers
            try:
                data=int(data)
            except:
                pass
        #Append the data to the empty list of the i'th column
        col[i][1].append(data)
        #Increment i for the next column
        i+=1

In [7]:
Dict={title:column for (title,column) in col}
df=pd.DataFrame(Dict)

In [8]:
df

                              Country  # of TV Shows             # of Movies
0                       United States           1326  View list         4339
1                      American Samoa           1078                    4573
2                         Puerto Rico           1073                    3807
3                          Martinique            803                    3736
4                          Guadeloupe            769                    3731
5                       French Guiana            803                    3710
6                     Benin (Dahomey)            462                    3171
7                   Equatorial Guinea            204                     488
8                            Anguilla            656                    2931
9              British Virgin Islands            666                    2940
10           Turks And Caicos Islands            696                    2899
11                            Jamaica            652                    2893
12   Saint Vincent And The Grenadines            655                    2888
13                           Dominica            649                    2889
14                Trinidad and Tobago            686                    2879
15                            Grenada            653                    2896
16              Saint Kitts And Nevis            653                    2879
17                Antigua and Barbuda            646                    2888
18                           Suriname            637                    2853
19                 Dominican Republic            646                    2847
20                              Haiti            636                    2829
21                           Honduras            638                    2834
22                        El Salvador            634                    2835
23                          Nicaragua            636                    2832
24                               Peru            636                    2831
25                            Ecuador            634                    2836
26                           Paraguay            640                    2826
27                             Panama            656                    2882
28                            Bahamas            647                    2687
29                             Canada            629                    2942
..                                ...            ...        ...          ...
182                          Zimbabwe            208                     483
183                           Morocco            173                     440
184                       Ivory Coast            200                     511
185                      Cook Islands            433                    1508
186                 Djibouti Republic            172                     440
187                         Gibraltar            581                     227
188                            Guyana            651                    2858
189                          Kiribati            408                    1512
190  Lao People’s Democratic Republic            548                     206
191                       Saint Lucia            652                    2920
192                     Liechtenstein            365                    1240
193                           Liberia            205                     486
194                            Monaco            314                    1309
195                   Myanmar (Burma)            208                     546
196                             Macao            145                     427
197                        Montserrat            661                    2967
198                          Maldives            210                     515
199                     New Caledonia            384                    1641
200                              Niue            399                    1359
201         Saint Pierre and Miquelon            219                     902
202                  Pitcairn Islands            172                     336
203                   Solomon Islands            416                    1510
204                 Saint Helena, ATC            181                     348
205                        San Marino            218                     884
206              Sao Tome and Pricipe            209                     489
207                   Tokelau Islands            428                    1466
208                             Tonga            403                    1490
209                            Tuvalu            375                    1320
210           Vatican City (Holy See)            191                     885
211                             Samoa            416                    1509

[212 rows x 4 columns]

In [9]:
df.to_csv("scraperesults.csv")